[package]
name = "launch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.7.0"
bevy_rapier2d = { version = "0.14.0", features = [ "enhanced-determinism" ]}
rand = { version = "0.8.5", features = ["small_rng"] }
rand_pcg = "0.3.1"
rand_seeder = "0.2.3"
rocksdb = "0.18.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.81"
futures = "0.3"
tokio = "1.19.2"
libp2p = "0.45.1"
async-std = {version = "1.12.0", features = ["attributes"]}
env_logger = "0.9.0"
clap = {version = "3.2.6", features = [ "derive" ]}
async-trait = "0.1.56"